"""Markdown export of an investigation (pinned findings + corpus-wide conflict register)."""
from __future__ import annotations

import datetime as dt
import re

from app.utils.text import normalize_ws


def _loc(c: dict) -> str:
    bits = [c["doc_name"]]
    if c.get("page"):
        bits.append(f"p.{c['page']}")
    if c.get("section"):
        bits.append(f"section \"{c['section']}\"")
    return ", ".join(bits)


def render_markdown(notes: list[dict], documents: list[dict], conflicts: list[dict], title: str = "Investigation report") -> str:
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    out = [f"# {title}", f"_Generated by DocSherlock {now} - {len(documents)} document(s), {len(notes)} finding(s)_", ""]
    out.append("## Documents reviewed")
    for d in documents:
        extra = []
        if d.get("doc_date"):
            extra.append(f"dated {d['doc_date']}")
        if d.get("ocr_used"):
            extra.append(f"OCR {d['ocr_conf']:.0%}" if d.get("ocr_conf") is not None else "OCR")
        out.append(f"- **{d['name']}** ({d['n_pages']} page{'s' if d['n_pages'] != 1 else ''}{', ' + ', '.join(extra) if extra else ''})")
    out.append("")
    out.append("## Findings")
    if not notes:
        out.append("_No questions asked yet._")
    for i, n in enumerate(notes, 1):
        r = n["result"]
        conf = r.get("confidence", {})
        out.append(f"### {i}. {r['question']}")
        status = {"answered": "Answered", "partial": "Partially answered", "conflict": "SOURCES CONFLICT", "insufficient": "Not found / insufficient evidence"}.get(r["status"], r["status"])
        out.append(f"**Status:** {status} - **Uncertainty level:** {r.get('level') or conf.get('label', '?')}")
        out.append("")
        out.append(re.sub(r"\[(S\d+)\]", r"[\1]", r["answer"]))
        out.append("")
        for cl in r.get("conflicts", []):
            if cl.get("resolution"):
                out.append(f"> **What might explain it (inference, not stated in the documents):** {cl['resolution']}")
                out.append("")
        if r.get("caveats"):
            out.append("**Caveats**")
            out += [f"- {c}" for c in r["caveats"]]
            out.append("")
        if r.get("citations"):
            out.append("**Sources**")
            for c in r["citations"]:
                tag = {"conflict": " (conflicting)", "lead": " (related, not an answer)"}.get(c.get("role"), "")
                out.append(f"- [{c['id']}] {_loc(c)}{tag}: \"{normalize_ws(c['quote'])}\"")
            out.append("")
        if n.get("comment"):
            out.append(f"> **Analyst note:** {n['comment']}")
            out.append("")
    out.append("## Conflict register (all documents)")
    if not conflicts:
        out.append("_No conflicts detected between the indexed documents._")
    for c in conflicts:
        vals = " vs ".join(f"\"{p['value']}\"" for p in c["positions"])
        out.append(f"- **[{c['severity'].upper()}]** {', '.join(c['topic'][:3]) or 'statement'}: {vals}")
        for p in c["positions"]:
            for src in p["sources"]:
                out.append(f"  - \"{p['value']}\" - {_loc(src)}" + (f" (dated {src['doc_date']})" if src.get("doc_date") else ""))
        if c.get("resolution"):
            out.append(f"  - _{c['resolution']}_")
    out.append("")
    out.append("_Generated by DocSherlock. Answers are limited to the uploaded documents; verify critical figures against the originals._")
    return "\n".join(out)
